# File: .github/workflows/release-please.yml
name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write      # for creating commits, tags, and releases
  pull-requests: write # for opening release PRs

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Run Release Please
        uses: googleapis/release-please@v4
        with:
          release-type: python

